<?php

define('PRECO_GOLD_LUNETA', 200);
define('PRECO_DOBRAO_LUNETA', 480);

define('PRECO_GOLD_CONHECIMENTO', 100);
define('PRECO_DOBRAO_CONHECIMENTO', 240);

define('PRECO_GOLD_COUP_DE_BURST', 100);
define('PRECO_DOBRAO_COUP_DE_BURST', 240);

define('PRECO_GOLD_COUP_DE_BURST_INSTANTANEO', 20);
define('PRECO_DOBRAO_COUP_DE_BURST_INSTANTANEO', 30);

define('PRECO_GOLD_TATICAS', 200);
define('PRECO_DOBRAO_TATICAS', 480);

define('PRECO_GOLD_CAMUFLAGEM', 10);
define('PRECO_DOBRAO_CAMUFLAGEM', 20);

define('PRECO_GOLD_RENOMEAR_TRIPULACAO', 1500);
define('PRECO_DOBRAO_RENOMEAR_TRIPULACAO', 1800);

define('PRECO_GOLD_TROCAR_FACCAO', 2000);
define('PRECO_DOBRAO_TROCAR_FACCAO', 2400);

define('PRECO_GOLD_FINALIZAR_TRATAMENTO_HOSPITAL', 1);
define('PRECO_DOBRAO_FINALIZAR_TRATAMENTO_HOSPITAL', 5);

define('PRECO_GOLD_ISCA_10', 10);
define('PRECO_DOBRAO_ISCA_10', 30);

define('PRECO_GOLD_ISCA_130', 100);
define('PRECO_DOBRAO_ISCA_130', 300);

define('PRECO_GOLD_RESET_AKUMA', 0); // 100
define('PRECO_DOBRAO_RESET_AKUMA', 120);

define('PRECO_GOLD_REDEFINE_AKUMA', 0); // 10
define('PRECO_DOBRAO_REDEFINE_AKUMA', 30);

define('PRECO_GOLD_RESET_ATRIBUTOS', 0); // 5
define('PRECO_DOBRAO_RESET_ATRIBUTOS', 20);

define('PRECO_GOLD_RESET_CLASSE', 0); // 15
define('PRECO_DOBRAO_RESET_CLASSE', 30);

define('PRECO_GOLD_RESET_DISPOSICAO', 20);
define('PRECO_DOBRAO_RESET_DISPOSICAO', 24);

define('PRECO_GOLD_RESET_HAKI', 0); // 15
define('PRECO_DOBRAO_RESET_HAKI', 30);

define('PRECO_GOLD_TREINAR_HAKI', 1);
define('PRECO_DOBRAO_TREINAR_HAKI', 2);

define('PRECO_GOLD_RESET_NOME_PERSONAGEM', 300);
define('PRECO_DOBRAO_RESET_NOME_PERSONAGEM', 360);

define('PRECO_GOLD_RESET_PROFISSAO', 0); // 15
define('PRECO_DOBRAO_RESET_PROFISSAO', 30);

define('PRECO_GOLD_VIAJA_RETORNO', 10);
define('PRECO_DOBRAO_VIAJA_RETORNO', 20);

define('PRECO_MODIFICADOR_RECRUTAR_LVL_ALTO', 1);
define('PRECO_MODIFICADOR_DOBRAO_RECRUTAR_LVL_ALTO', 5);

define('PRECO_GOLD_RECUPERAR_OFENSIVA_MESTRE_HAKI', 1);
define('PRECO_DOBRAO_RECUPERAR_OFENSIVA_MESTRE_HAKI', 2);

define('PRECO_GOLD_FERREIRO_VIP', 1);
define('PRECO_DOBRAO_FERREIRO_VIP', 10);

define('PRECO_BERRIES_TRANSPORTE_ILHA_RETORNO', 2000000);

define('PRECO_GOLD_TROCAR_PERSONAGEM', 300);
define('PRECO_DOBRAO_TROCAR_PERSONAGEM', 360);

define('PRECO_GOLD_TROCAR_BANDEIRA', 300);
define('PRECO_DOBRAO_TROCAR_BANDEIRA', 360);

define('PRECO_GOLD_RESETAR_INFLUENCIA', 5);
define('PRECO_DOBRAO_RESETAR_INFLUENCIA', 6);

define('PRECO_GOLD_USAR_FORMACOES', 100);
define('PRECO_DOBRAO_USAR_FORMACOES', 120);

define('PRECO_GOLD_CUSTOMIZAR_SKILL', 1);
define('PRECO_DOBRAO_CUSTOMIZAR_SKILL', 5);

define('PRECO_GOLD_SELO_EXP', 1);