INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'Rei dos Piratas',0,'Rainha dos Piratas'),
	 (0,0,'Almirante de Frota',0,'Almirante de Frota'),
	 (0,0,'A cabeça de 100 milhões de Berries',0,'A cabeça de 100 milhões de Berries'),
	 (0,0,'A cabeça de 200 milhões de Berries',0,'A cabeça de 200 milhões de Berries'),
	 (0,0,'A cabeça de 300 milhões de Berries',0,'A cabeça de 300 milhões de Berries'),
	 (0,0,'A cabeça de 400 milhões de Berries',0,'A cabeça de 400 milhões de Berries'),
	 (0,0,'A cabeça de 500 milhões de Berries',0,'A cabeça de 500 milhões de Berries'),
	 (0,0,'A cabeça de 600 milhões de Berries',0,'A cabeça de 600 milhões de Berries'),
	 (0,0,'O melhor Espadachim do mundo',0,'A melhor Espadachim do mundo'),
	 (0,0,'O melhor Lutador do mundo',0,'A melhor Lutadora do mundo');
INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'O melhor Atirador do mundo',0,'A melhor Atiradora do mundo'),
	 (0,0,'Perna Vermelha',0,'Perna Vermelha'),
	 (0,0,'Perna Negra',0,'Perna Negra'),
	 (0,0,'Estilo Santoryuu',0,'Estilo Santoryuu'),
	 (0,0,'Mestre Santoryuu',0,'Mestre Santoryuu'),
	 (0,0,'O Retalhador',0,'A Retalhadora'),
	 (0,0,'Mestre do corte',0,'Mestre do corte'),
	 (0,0,'Grande Atirador',0,'Grande Atiradora'),
	 (0,0,'O Rei Atirador',0,'A Rainha Atiradora'),
	 (0,0,'Usuário de fogo',0,'Usuária de fogo');
INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'Mestre do Fogo',0,'Mestre do Fogo'),
	 (0,0,'Usuário de Água',0,'Usuária de Água'),
	 (0,0,'Controlador de Água',0,'Controladora de Água'),
	 (0,0,'Punhos de Ferro',0,'Punhos de Ferro'),
	 (0,0,'Punhos de Aço',0,'Punhos de Aço'),
	 (0,0,'O Caçador de Piratas',1,'A Caçadora de Piratas'),
	 (0,0,'O Caçador de Ladrões',1,'A Caçadora de Ladrões'),
	 (0,0,'O Justiceiro',1,'A Justiceira'),
	 (0,0,'O Palhaço',1,'A Palhaça'),
	 (0,0,'Unhas de Gato',1,'Unhas de Gato');
INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'O cozinheiro',1,'A cozinheira'),
	 (0,0,'Dentes de Serrote',1,'Dentes de Serrote'),
	 (0,0,'O Sonhador',1,'A Sonhadora'),
	 (0,0,'O Mentiroso',1,'A Mentirosa'),
	 (0,0,'O Trapaceiro',1,'A Trapaceira'),
	 (0,0,'G',1,'G'),
	 (0,0,'O Catarrento',1,'A Catarrenta'),
	 (0,0,'O Friorento',1,'A Friorenta'),
	 (0,0,'O Boxeador',1,'A Boxeadora'),
	 (0,0,'O Musculoso',1,'A Musculosa');
INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'Pena de Pardal',1,'Pena de Pardal'),
	 (0,0,'O Rei do Pop',1,'A Rainha do Pop'),
	 (0,0,'Punhos de Ferro',1,'Punhos de Ferro'),
	 (0,0,'Mãos de tesoura',1,'Mãos de tesoura'),
	 (0,0,'Gênio Tático',1,'Gênio Tático'),
	 (0,0,'O Vilão',1,'A Vilã'),
	 (0,0,'O Bandido',1,'A Bandida'),
	 (0,0,'Artista Marcial',1,'Artista Marcial'),
	 (0,0,'O Explorador',1,'A Exploradora'),
	 (0,0,'O Assustador',1,'A Assustadora');
INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'O Homem de Ferro',1,'A Mulher de Ferro'),
	 (0,0,'O Domador de Leões',1,'A Domadora de Leões'),
	 (0,0,'O Homem Macaco',1,'A Mulher Macaco'),
	 (0,0,'O Poderoso Chefão',1,'A Poderosa Chefã'),
	 (0,0,'Envolvido em uma grande promessa',1,'Envolvida em uma grande promessa'),
	 (0,0,'O Caçador de Recompensas',1,'A Caçadora de Recompensas'),
	 (0,0,'O Gigante',1,'A Gigante'),
	 (0,0,'O Médico',1,'A Médica'),
	 (0,0,'Metamorfose Ambulante',1,'Metamorfose Ambulante'),
	 (0,0,'O Grande',1,'A Grande');
INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'O Impaciente',1,'A Impaciente'),
	 (0,0,'O Rebelde',1,'A Rebelde'),
	 (0,0,'O Impiedoso',1,'A Impiedosa'),
	 (0,0,'O Verdadeiro',1,'A Verdadeira'),
	 (0,0,'A Raposa',1,'A Raposa'),
	 (0,0,'O Cirurgião',1,'A Cirurgiã'),
	 (0,0,'O Carpinteiro',1,'A Carpinteira'),
	 (0,0,'Da Pior Geração',1,'Da Pior Geração'),
	 (0,0,'O Anti-Tenryuubito',1,'A Anti-Tenryuubito'),
	 (0,0,'Choque Térmico',1,'Choque Térmico');
INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'Sopro Congelante',1,'Sopro Congelante'),
	 (0,0,'Senhor dos Raios',1,'Senhora dos Raios'),
	 (0,0,'Chefe de Laftel',1,'Chefe de Laftel'),
	 (0,0,'O Caçador de Insetos',1,'A Caçadora de Insetos'),
	 (0,0,'O Demônio Vermelho',1,'A Demônio Vermelho'),
	 (0,0,'O Sedento por Sangue',1,'A Sedenta por Sangue'),
	 (0,0,'O Desbravador',1,'A Desbravadora'),
	 (0,0,'O Conquistador',1,'A Conquistadora'),
	 (0,0,'Yonkou',0,'Yonkou'),
	 (0,0,'Almirante',0,'Almirante');
INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'das Cem Feras',1,'das Cem Feras'),
	 (0,0,'Animal selvagem',1,'Animal selvagem'),
	 (0,0,'A muralha',1,'A muralha'),
	 (0,0,'O Destruidor',1,'A Destruidora'),
	 (0,0,'Caçador',1,'Caçadora'),
	 (0,0,'O Bom Companheiro',1,'A Boa Companheira'),
	 (0,0,'A Calamidade',1,'A Calamidade'),
	 (0,0,'O Deus da Guerra',1,'A Deusa da Guerra'),
	 (0,0,'A Besta Indomável',1,'A Besta Indomável'),
	 (0,0,'O Caçador Branco',1,'A Caçadora Branca');
INSERT INTO sugoi.tb_titulos (bonus_atr,bonus_atr_quant,nome,compartilhavel,nome_f) VALUES
	 (0,0,'O Lobo do mar',1,'A Loba do mar'),
	 (0,0,'Cria do Demônio',1,'Cria do Demônio'),
	 (0,0,'Punhos Negros',1,'Punhos Negros'),
	 (0,0,'O Paizão',1,'A Mãezona'),
	 (0,0,'Quebrador de Correntes',1,'Quebradora de Correntes'),
	 (0,0,'O Rancoroso',1,'A Rancorosa'),
	 (0,0,'Assassino do submundo',1,'Assassina do submundo'),
	 (0,0,'Campeão do Coliseu',1,'Campeã do Coliseu'),
	 (0,0,'Rushador Sugoi!',0,'Rushadora Sugoi!'),
	 (0,0,'Campeão do 1º torneio',0,NULL);
