INSERT INTO sugoi.tb_variavel_global (variavel,valor_int,valor_varchar) VALUES
	 ('BALANCO_VENDA_DOBRAO',NULL,NULL),
	 ('RDP',NULL,NULL),
	 ('ADF',NULL,NULL),
	 ('VENCEDORES_ERA_PIRATA',NULL,NULL),
	 ('VENCEDORES_ERA_MARINHA',NULL,NULL),
	 ('IDS_ACESSO_IMPEL_DOWN',NULL,NULL),
	 ('IDS_ACESSO_ENIES_LOBBY',NULL,NULL),
	 ('ALMIRANTES',NULL,NULL),
	 ('YONKOUS',NULL,NULL),
	 ('EVENTO_PERIODICO_ATIVO',NULL,'eventoLadroesTesouro');
INSERT INTO sugoi.tb_variavel_global (variavel,valor_int,valor_varchar) VALUES
	 ('VENCEDORES_INCURSAO',NULL,NULL),
	 ('TOTAL_HAKI_TREINOS',NULL,NULL),
	 ('VARIAVEL_COLISEU',NULL,NULL),
	 ('ERA_ATUAL',NULL,'2024-2'),
	 ('BATALHA_PONEGLYPH_ATUAL',NULL,'2024-6'),
	 ('ULTIMO_RESET_HP_BOSS',1718228698,NULL);
