<?php
define('SISTEMA_HOSPITAL', 'SISTEMA_HOSPITAL');
define('SISTEMA_ACADEMIA', 'SISTEMA_ACADEMIA');
define('SISTEMA_VISAO_GERAL_TRIPULACAO', 'SISTEMA_VISAO_GERAL_TRIPULACAO');
define('SISTEMA_ESTALEIRO', 'SISTEMA_ESTALEIRO');
define('SISTEMA_BANDEIRA', 'SISTEMA_BANDEIRA');
define('SISTEMA_RECRUTAR_TRIPULANTE', 'SISTEMA_RECRUTAR_TRIPULANTE');
define('SISTEMA_INCURSOES', 'SISTEMA_INCURSOES');
define('SISTEMA_TESOUROS', 'SISTEMA_TESOUROS');
define('SISTEMA_PROFISSOES', 'SISTEMA_PROFISSOES');
define('SISTEMA_PESQUISAS', 'SISTEMA_PESQUISAS');
define('SISTEMA_RESTAURANTE', 'SISTEMA_RESTAURANTE');
define('SISTEMA_CACA', 'SISTEMA_CACA');
define('SISTEMA_OCEANO', 'SISTEMA_OCEANO');
define('SISTEMA_CALENDARIO', 'SISTEMA_CALENDARIO');
define('SISTEMA_SERVICO_TRANSPORTE', 'SISTEMA_SERVICO_TRANSPORTE');
define('SISTEMA_DOMINIO_ILHA', 'SISTEMA_DOMINIO_ILHA');
define('SISTEMA_ALIANCAS', 'SISTEMA_ALIANCAS');
define('SISTEMA_EVENTOS', 'SISTEMA_EVENTOS');
define('SISTEMA_TRIPULANTES_FORA_BARCO', 'SISTEMA_TRIPULANTES_FORA_BARCO');
define('SISTEMA_HAKI', 'SISTEMA_HAKI');

