<?php
define('TIPO_SKILL_ATAQUE_CLASSE', 1);
define('TIPO_SKILL_BUFF_CLASSE', 2);
define('TIPO_SKILL_PASSIVA_CLASSE', 3);
define('TIPO_SKILL_ATAQUE_PROFISSAO', 4);
define('TIPO_SKILL_BUFF_PROFISSAO', 5);
define('TIPO_SKILL_PASSIVA_PROFISSAO', 6);
define('TIPO_SKILL_ATAQUE_AKUMA', 7);
define('TIPO_SKILL_BUFF_AKUMA', 8);
define('TIPO_SKILL_PASSIVA_AKUMA', 9);
define('TIPO_SKILL_MEDICAMENTO', 10);

define('COD_SKILL_SOCO', 1);

define('SPECIAL_EFFECT_SANGRAMENTO', 1);
define('SPECIAL_EFFECT_VENENO', 2);
define('SPECIAL_EFFECT_MACHUCADO_JOELHO', 3);
define('SPECIAL_EFFECT_PONTO_FRACO', 4);

define('SPECIAL_TARGET_SELF', 1);
define('SPECIAL_TARGET_TARGET', 2);

define('SPECIAL_APPLY_TYPE_APPLY', 1);
define('SPECIAL_APPLY_TYPE_REMOVE', 2);

define('PRECO_BERRIES_REMOVER_SPECIAL_EFFECT', 100000);


define('TIPO_EFEITO_POSITIVO', 'POSITIVO');
define('TIPO_EFEITO_NEGATIVO', 'NEGATIVO');

define('ATRIBUTO_ATACANTE_ACERTO_CRITICO', 'ATACANTE_ACERTO_CRITICO');

define('TIPO_ALVO_EFEITO_ATACANTE', 'ATACANTE');
define('TIPO_ALVO_EFEITO_ALVO', 'ALVO');
define('TIPO_ALVO_EFEITO_ALIADO_MENOR_VIDA', 'ALIADO_MENOR_VIDA');
define('TIPO_ALVO_EFEITO_INIMIGO_MENOR_VIDA', 'INIMIGO_MENOR_VIDA');
define('TIPO_ALVO_EFEITO_ALIADO_MAIOR_VIDA', 'ALIADO_MAIOR_VIDA');
define('TIPO_ALVO_EFEITO_INIMIGO_MAIOR_VIDA', 'INIMIGO_MAIOR_VIDA');
define('TIPO_ALVO_EFEITO_ALIADO_ALEATORIO', 'ALIADO_ALEATORIO');
define('TIPO_ALVO_EFEITO_INIMIGO_ALEATORIO', 'INIMIGO_ALEATORIO');
define('TIPO_ALVO_EFEITO_ALIADO_COM_EFEITO_NEGATIVO', 'ALIADO_COM_EFEITO_NEGATIVO');
define('TIPO_ALVO_EFEITO_INIMIGO_COM_EFEITO_NEGATIVO', 'INIMIGO_COM_EFEITO_NEGATIVO');
define('TIPO_ALVO_EFEITO_ALIADO_COM_EFEITO_POSITIVO', 'ALIADO_COM_EFEITO_POSITIVO');
define('TIPO_ALVO_EFEITO_INIMIGO_COM_EFEITO_POSITIVO', 'INIMIGO_COM_EFEITO_POSITIVO');
define('TIPO_ALVO_EFEITO_TODOS', 'TODOS');
define('TIPO_ALVO_EFEITO_TODOS_ALIADOS', 'TODOS_ALIADOS');
define('TIPO_ALVO_EFEITO_TODOS_IMIMIGOS', 'TODOS_IMIMIGOS');
