<?php
define('PRECO_GOLD_LUNETA', 150);

define('PRECO_GOLD_CONHECIMENTO', 750);

define('PRECO_GOLD_COUP_DE_BURST', 250);

define('PRECO_GOLD_COUP_DE_BURST_INSTANTANEO', 20);

define('PRECO_GOLD_TATICAS', 250);

define('PRECO_GOLD_CAMUFLAGEM', 500);

define('PRECO_GOLD_RENOMEAR_TRIPULACAO', 500);

define('PRECO_GOLD_TROCAR_FACCAO', 500);

define('PRECO_GOLD_FINALIZAR_TRATAMENTO_HOSPITAL', 50);

define('PRECO_GOLD_ISCA_10', 10);

define('PRECO_GOLD_ISCA_130', 60);

define('PRECO_GOLD_RESET_AKUMA', 100); // 100

define('PRECO_GOLD_REDEFINE_AKUMA', 50); // 10

define('PRECO_GOLD_RESET_ATRIBUTOS', 20); // 5

define('PRECO_GOLD_RESET_CLASSE', 0); // 15

define('PRECO_GOLD_RESET_DISPOSICAO', 100);

define('PRECO_GOLD_RESET_HAKI', 100); // 15

define('PRECO_GOLD_TREINAR_HAKI', 1);

define('PRECO_GOLD_RESET_NOME_PERSONAGEM', 250);

define('PRECO_GOLD_RESET_PROFISSAO', 100); // 15

define('PRECO_GOLD_VIAJA_RETORNO', 200);

define('PRECO_MODIFICADOR_RECRUTAR_LVL_ALTO', 15);

define('PRECO_GOLD_RECUPERAR_OFENSIVA_MESTRE_HAKI', 1);

define('PRECO_GOLD_FERREIRO_VIP', 50);

define('PRECO_BERRIES_TRANSPORTE_ILHA_RETORNO', 2000000);

define('PRECO_GOLD_TROCAR_PERSONAGEM', 150);

define('PRECO_GOLD_TROCAR_BANDEIRA', 250);

define('PRECO_GOLD_RESETAR_INFLUENCIA', 200);

define('PRECO_GOLD_USAR_FORMACOES', 100);

define('PRECO_GOLD_CUSTOMIZAR_SKILL', 2);

define('PRECO_GOLD_SELO_EXP', 25);
